#!/bin/bash

FZF_PATH="$HOME/.fzf"

if [[ `uname` == 'Darwin' ]]
then
    # Install Homebrew & Cask
    if [ ! hash git 2>/dev/null ]; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        echo "HomeBrew is already installed!"
    fi

    brew tap Homebrew/bundle
    brew bundle --verbose
else
    echo "This script supports only MacOs installation"
fi


# Link dotfiles
./sync

#Running further commands for some specific packages

# Note: fzf section should be after sync execution above -- otherwise it will create a new .zsh file if it's not present!
#fzf is used in both commandline and Vim
#Ideally installing vim plugins would automatically pull down fzf as well, but loading it before if vim is not opened and still zsh keycompletions are good

if [ ! -d "$FZF_PATH" ]; then
	git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_PATH
	$FZF_PATH/install --all
else 
	echo "FZF already installed"
fi

