#!/usr/bin/env bash

export DOTFILES_ROOT="$HOME/dotfiles"

warning() {
  local message="$1"
  printf "\e[33m${message}\e[0m\n"
}

links="zshrc vimrc"

for filename in $links; do

  file_in_dotfiles="$DOTFILES_ROOT/$filename"
  file_in_home="$HOME/.$filename"

  if [[ -e $file_in_home ]]; then
    if [[ ! -L $file_in_home ]]; then
      warning "$file_in_home exists but is not a symlink."
    fi
  else
    echo "Creating symlink at $file_in_home"
    ln -s "$file_in_dotfiles" "$file_in_home"
  fi
done


